databases:
  - name: teachkadb
    plan: free
    databaseName: teachka
    user: teachka

services:
  - type: web
    plan: free
    name: teachka-web
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn teachkaBaseProject.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: teachkadb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4